NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

#### Array
An array is a data structure that stores values of same data type. In Python, list can contain values corresponding to different data types but array can only contain values corresponding to same data type

In [1]:
# pip install numpy or conda install numpy - for manually install

#Import Mumpy
import numpy as np

#### Single Dimension array

In [2]:
my_lst=[1,2,3,4,5,6]
arr1 = np.array(my_lst)

print(arr1)
print(type(arr1))
print(arr1.shape) #know only no of columns for 1D array

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [3]:
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
arr2 = arr1.reshape(3,2) #convert shape with same no of elements, otherwise error
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Multinested / Multi Dimension array

In [5]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr3 = np.array([my_lst1,my_lst2,my_lst3])

print(arr3)
print(type(arr3))
print(arr3.shape) #know no of row & column

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
<class 'numpy.ndarray'>
(3, 5)


In [6]:
arr3

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [7]:
arr4 = arr3.reshape(5,3) #Convert shape with same no of elements, otherwise error
arr4

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

#### 1D array Indexing

In [8]:
arr1

array([1, 2, 3, 4, 5, 6])

In [9]:
arr1[:] #All elements

array([1, 2, 3, 4, 5, 6])

In [10]:
arr1[4] #Single element

5

In [11]:
arr1[3:] #As 1d arry so, from 3rd column to last column

array([4, 5, 6])

#### 2D array Indexing

In [12]:
arr3

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr3[:] #All elements

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [14]:
arr3[1:,3:] #From 1st row to last row and from 3rd column to last column

array([[5, 6],
       [8, 9]])

In [15]:
arr3[:,3:] #For all rows, from 3rd column to last column

array([[4, 5],
       [5, 6],
       [8, 9]])

In [16]:
arr3[1:,:] #From 1st row to last row, for all columns

array([[2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [17]:
arr3[0:2,3:5] #Specific part

array([[4, 5],
       [5, 6]])

#### Build in functions

In [18]:
#Initialize
arr = np.linspace(1,10,6) #With n no of equally spaced values in the range
print("1D Linspace: ",arr)
arr1 = np.linspace(1,10,6).reshape(2,3) #With n no of equally spaced values in the range with shape
print("nD Linspace:\n",arr1)

print("\n")

arr = np.arange(1,10,1) #With start, end before, step values
print("1D Initialize: ",arr)
arr1 = np.arange(1,10,1).reshape(3,3) #With start, end before, step values with shape
print("nD Initialize:\n",arr1)

print("\n")

arr[4:]=0 #Replaced values and updated
print("1D Updated:\n",arr)
arr1[1:,1:]=0 #Replaced values and updated with shape
print("nD Updated:\n",arr1)

1D Linspace:  [ 1.   2.8  4.6  6.4  8.2 10. ]
nD Linspace:
 [[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]


1D Initialize:  [1 2 3 4 5 6 7 8 9]
nD Initialize:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


1D Updated:
 [1 2 3 4 0 0 0 0 0]
nD Updated:
 [[1 2 3]
 [4 0 0]
 [7 0 0]]


In [19]:
#copy() function and broadcasting for 1D, nD also possible
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Actual arr: ",arr)
print("After direct copy - (reference is also copying)")
arr1= arr
arr1[4:] = 0
print("arr: ",arr)
print("arr1: ",arr1)

print("\n")

arr = np.array([1,2,3,4,5,6,7,8,9])
print("Actual arr: ",arr)
print("After copy by copy() - (copying in new reference)")
arr1= arr.copy()
arr1[4:] = 0
print("arr: ",arr)
print("arr1: ",arr1)

Actual arr:  [1 2 3 4 5 6 7 8 9]
After direct copy - (reference is also copying)
arr:  [1 2 3 4 0 0 0 0 0]
arr1:  [1 2 3 4 0 0 0 0 0]


Actual arr:  [1 2 3 4 5 6 7 8 9]
After copy by copy() - (copying in new reference)
arr:  [1 2 3 4 5 6 7 8 9]
arr1:  [1 2 3 4 0 0 0 0 0]


In [20]:
arr = np.ones(5) #Initialize will all 1 with default float type
print(arr)

arr = np.ones((2,3),dtype=int)
print(arr)

[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]]


In [21]:
arr = np.random.randint(1,100,8) #default 1D array
print("Definite no of Random Integers within a range:\n",arr)

print("\n")

arr = np.random.randint(1,100,8).reshape(2,4)
print("Definite no of Random Integers within a Range with Shape:\n",arr)

print("\n")

arr = np.random.random_sample((2,5)) #default interval [0,1) and shape optional
print("Random Floats with Shape:\n",arr)

print("\n")

arr = np.random.rand(3,4) #default interval [0,1)
print("Random Sample from Uniform Distribution with Shape:\n",arr)

print("\n")

arr = np.random.randn(3,4)
print("Random Sample from Standard Normal Distribution with Shape:\n",arr)

Definite no of Random Integers within a range:
 [72 35 82 33 64 52 94 88]


Definite no of Random Integers within a Range with Shape:
 [[88 35 76 25]
 [ 3 88  2 75]]


Random Floats with Shape:
 [[0.30646409 0.90274554 0.22210068 0.46209245 0.99929203]
 [0.12063093 0.34473951 0.27391851 0.50428395 0.1341161 ]]


Random Sample from Uniform Distribution with Shape:
 [[0.03861068 0.49404621 0.02740142 0.35754029]
 [0.58093402 0.44863046 0.32756581 0.68461918]
 [0.15438759 0.65030393 0.60325935 0.17807852]]


Random Sample from Standard Normal Distribution with Shape:
 [[ 0.62770403 -1.24629493  0.29413905  0.59553562]
 [ 0.49028797  0.81990155  2.90390159  0.98166222]
 [-2.01682907  0.48131821  0.85393762  0.2309463 ]]


#### Basic Conditions and Operations

In [23]:
val = 3

arr = np.array([1,2,3,4,5,6,7,8,9])
print("Actual arr: ",arr)

print("\n")

print("Summation with all elements: ",arr+val)
print("Substrtaction with all elements: ",arr-val)
print("Multiplication with all elements: ",arr*val)
print("Division with all elements: ",arr/val)
print("Reminder of all elements: ",arr%val)

print("\n")

print("Checking condition with all elements: ",arr<val)

#Extract elements with condition
print("Elements less than {} are {} ".format(val,arr[arr<val]))

Actual arr:  [1 2 3 4 5 6 7 8 9]


Summation with all elements:  [ 4  5  6  7  8  9 10 11 12]
Substrtaction with all elements:  [-2 -1  0  1  2  3  4  5  6]
Multiplication with all elements:  [ 3  6  9 12 15 18 21 24 27]
Division with all elements:  [0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
 2.33333333 2.66666667 3.        ]
Reminder of all elements:  [1 2 0 1 2 0 1 2 0]


Checking condition with all elements:  [ True  True False False False False False False False]
Elements less than 3 are [1 2] 
